name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
    test:
      name: debian
      runs-on: ubuntu-latest
      environment: testing
      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build the postxml image
          run: docker build -t albaike/postxml:latest .

        - name: Extract the debian package
          run:
            docker create --name temp albaike/postxml:latest
            docker cp temp:/postxml/postgresql-16-postxml_1.0-1_amd64.deb .
            docker rm temp


        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false

        - name: Upload Release Asset
          id: upload_release_asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./postgresql-16-postxml_1.0-1_amd64.deb
            asset_name: postgresql-16-postxml_1.0-1_amd64.deb