name: Test package

on:
  push:
    branches:
      - master

jobs:
    test:
      name: test
      runs-on: ubuntu-latest
      environment: testing
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build the postxml image
          run: docker build -t albaike/postxml:latest .

        - name: Build the test image
          run: docker build -t test -f Dockerfile.test .

        - name: Run the test
          run: docker run -e POSTGRES_PASSWORD=pw test